ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60

HEALTH = 100
MONEY = 650

# Enemy Constants
SPAWN_COOLDOWN = 400
KILL_REWARD = 1

#turret constants
TURRET_LEVELS = 4
BUY_COST = 200
UPGRADE_COST = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
DAMAGE = 5